package alfarezyyd.asclepius.model.option;

public enum LastEducation {
  ELEMENTARY_SCHOOL, JUNIOR_HIGH_SCHOOL, SENIOR_OR_VOCATIONAL_SCHOOL, DIPLOMA_3, BACHELOR_DEGREE, ASSOCIATE_DEGREE, MASTER_DEGREE

}
